Devsearsh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projects.urls')),
    path('',include('users.urls')),
    path('api/',include('api.urls')),

    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('reset_password_send/',auth_views.PasswordResetDoneView.as_view(template_name='reset_password_send.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passowrd_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_passord_complete/',auth_views.PasswordResetCompleteView.as_view(template_name = 'passowrd_reset_complete.html'),name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [

    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('',views.getRoutes),
    path('projects/',views.getProjects),
    path('projects/<str:pk>/',views.getProject),
    path('profiles/',views.getProfiles),
    path('profiles/<str:pk>',views.getProfile)
]

projects/urls.py
from django.urls import  path
from . import views

app_name = 'projects'
urlpatterns = [
    # path('',views.Home, name='home'),
    path('projects/',views.projects,name='projects'),
    path('project/<str:pk>',views.project, name='project'),
    path('create-project/',views.createProject, name='create-project'),
    path('update-project/<str:pk>',views.updateProject, name='update-project'),
    path('delete-project/<str:pk>',views.deleteProject, name='delete-project')
]

users/urls.py
from django.urls import path
from . import  views


app_name = 'users'
urlpatterns = [
    path('',views.profiles, name='profiles'),
    path('login/',views.loginUser, name='login'),
    path('register/',views.registerUser, name='register'),
    path('account/',views.userAccount, name='account'),
    path('add-skill/',views.addSkill,name='add-skill'),
    path('update-skill/<str:pk>/',views.updateSkill, name='update-skill'),
    path('delete-skill/<str:pk>',views.deleteSkill,name = 'delete-skill'),
    path('edit-account/',views.editAccount, name='edit-account'),
    path('logout/',views.logoutUser, name='logout'),
    path('profile/<str:pk>',views.userProfile, name= 'profile'),
    path('inbox/',views.inbox, name= 'inbox'),
    path('message/<str:pk>',views.viewMessage, name='message'),
    path('create-message/<str:pk>',views.createMessage,name='crate-message')

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True, blank=True )
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    username = models.CharField(max_length=200,null=True, blank=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(null=True, blank=True)
    location = models.CharField(max_length=200,blank=True, null=True)
    profile_image = models.ImageField(default='profiles/user-default.jpg',null=True,blank=True, upload_to='profiles/')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter =  models.CharField(max_length=200, blank=True, null=True)
    social_linkedin =  models.CharField(max_length=200, blank=True, null=True)
    social_youtube =  models.CharField(max_length=200, blank=True, null=True)
    social_website =  models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)
    class Meta:
        ordering =["created"]


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=False)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                         primary_key=True, editable=False)

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

users/views.py
from django.shortcuts import render, redirect
from .models import Profile,Skill,Message
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.db.models import Q
from .form import CustomUserCreationFrom,ProfileForm,SkillForm,MessageForm
from .utils import searchProfiles, paginateProfiles
# Create your views here.



def loginUser(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('users:profile')
    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User dose not exist!')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'users:account')
        else:
            messages.error(request,'username or pass incorrect')

    return render(request,'users/login_register.html')

def logoutUser(request):
    logout(request)
    messages.info(request,'User was logged out!')
    return redirect('users:login')



def registerUser(request):
    page = 'register'
    form = CustomUserCreationFrom()

    if request.method == 'POST':
        form = CustomUserCreationFrom(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request,'User save')
            login(request, user)
            return  redirect('users:edit-account')
        else:
            messages.error(request,'An error has occurred during registrations' )


    context= {
        'page': page,'form':form
    }
    return  render(request,'users/login_register.html',context)



def profiles(request):
    profiles , search_query = searchProfiles(request)

    custom_range, profiles = paginateProfiles(request,profiles,2)
    context = {'developers':profiles,'search_query':search_query,'custom_range':custom_range}
    return render(request,'users/profiles.html',context)


# @login_required(login_url='users:login')
def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)

    topSkills = profile.skill_set.exclude(description__exact="")
    otherSkills = profile.skill_set.filter(description="")
    context = {
        'profile':profile,'topSkills':topSkills,'otherSkills':otherSkills
    }
    return render(request,'users/user-profile.html',context)


@login_required(login_url='users:login')
def userAccount(request):
    profile = request.user.profile

    skills = profile.skill_set.all()
    projects = profile.project_set.all()

    context = {
        'profile':profile,'skills':skills,
        'projects':projects
    }
    return render(request,'users/account.html',context)

@login_required(login_url='users:login')
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            return redirect('users:account')
            messages.success(request,'Users has been edited')
        else:
            messages.error(request,'sdfsdf')

    context = {
        'form':form
    }
    return  render(request,'users/profile_form.html',context)


@login_required(login_url='users:login')
def addSkill(request):
    profile = request.user.profile
    form = SkillForm()
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request,'skill was add successfully!')
            return  redirect('users:account')
    context ={
        'form':form
    }
    return render(request,'users/skill_form.html',context)

@login_required(login_url='users:login')
def updateSkill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = SkillForm(instance=skill)

    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request,'skill was updated successfully!')
            return redirect('users:account')
    context = {
        'form':form
    }
    return render(request,'users/skill_form.html',context)

@login_required(login_url='users:login')
def deleteSkill(request,pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    if request.method =='POST':
        skill.delete()
        return redirect('users:account')
    context ={
        'object':skill
    }
    return render(request,'delete_template.html',context)

@login_required(login_url='users:login')
def inbox(request):
    profile = request.user.profile
    messageRequests = profile.messages.all()
    unreadCount = messageRequests.filter(is_read=False).count()
    context ={
        'messageRequests':messageRequests,'unreadCound':unreadCount
    }
    return render(request,'users/inbox.html',context)



@login_required(login_url='users:login')
def viewMessage(request, pk):
    profile = request.user.profile
    # message = Message.objects.get(id=pk)
    message = profile.messages.get(id=pk)
    if message.is_read == False:
        message.is_read = True
        message.save()
    context = {
        'message':message,
    }
    return render(request,'users/message.html',context)


@login_required(login_url='users:login')
def createMessage(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile
    except:
        sender = None

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email

            message.save()

            messages.success(request,'You message successfully sent!')
            return  redirect('users:profile', pk=recipient.id)


    context = {
        'recipient':recipient,'form':form
    }
    return render(request,'users/message_form.html',context)

users/templates/users/account.html
{% extends 'main.html' %}
{% block content %}
    <!-- Main Section -->
   <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:edit-account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.short_intro }}</p>
              <p class="dev__location">Based {{ profile.location }}</p>
              <ul class="dev__social">
                 {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                  {% endif %}
                {% if profile.social_youtube %}
                <li>
                  <a title="Stackoverflow" href="{{profile.social_github }}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {% endif %}
                 {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_github }}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
               {% endif %}
                 {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_github }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
               {% endif %}
                 {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_github }}" target="_blank"><i class="im im-globe"></i></a>
                </li>
              {% endif %}
              </ul>
            {% if request.user.profile.id != profile.id %}
              <a href="{% url 'users:crate-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
            {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'users:add-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
              {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{ skill.name }}</h4>
                <p>
                  {{ skill.description }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
              {% endfor %}

          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
              {% for project in projects %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'projects:project' project.id %}"><img src="{{ project.feautured_image.url }}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'projects:project' project.id %}">{{ project.title }}</a>
                <p>
                  {{ project.description|slice:"120" }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
              {% endfor %}

          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock%}

users/templates/users/inbox.html
{% extends 'main.html' %}
{% block content%}
     <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{ unreadCound }}</span>)</h3>
      <ul class="messages">
          {% for message in messageRequests %}
          {% if message.is_read == False %}
          <li class="message message--unread">
              {% else %}
               <li class="message">
          {% endif %}

          <a href="{% url 'users:message' message.id %}">
            <span class="message__author">{{ message.name }}</span>
            <span class="message__subject">{{ message.subject }}</span>
            <span class="message__date">{{ message.created }}</span>
          </a>

        </li>
        {% endfor %}
      </ul>
    </div>
  </main>
{%endblock %}

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    {% if page == 'register' %}
      <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account SignUp</h3>
          <p>Create a new developer account</p>
        </div>

        <form action="{% url 'users:register' %}" class="form auth__form"  method="post">
        {% csrf_token %}
          {% for field in form %}
          <div class="form__field">
            <label for="formInput#text">{{ field.label}} </label>
           {{ field }}

          {% if field.help_text %}
              <small>{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
                <p style="color: #e35f5f">{{ error }}</p>
              {% endfor %}
          </div>
         {% endfor %}

          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
          </div>
        </form>
        <div class="auth__alternative">
          <p>Already have an Account?</p>
          <a href="{% url 'users:login' %}">Log In</a>
        </div>
      </div>
    </div>


   {% else %}
     <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account Login</h3>
          <p>Hello Developer, Welcome Back!</p>
        </div>

        <form action=""  method="post" class="form auth__form">
            {% csrf_token %}
          <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="{% url 'reset_password' %}">Forget Password?</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'users:register' %}">Sign Up</a>
        </div>
      </div>
    </div>

    {% endif %}
{% endblock %}

users/templates/users/message.html
{% extends 'main.html' %}


{% block content %}
     <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'users:inbox' %}"><i class="im im-angle-left"></i></a>
        <h4 class="message__subject">{{ message.subject }}</h4>
          <a href="{% url 'users:profile' message.sender.id %}" class="message__author">{{ message.name}}</a>
          <p class="message__date">{{ message.created }}</p>
          <div class="message__body">
            {{ message.body|linebreaksbr }}
          </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

     <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'users:profiles' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                value="{{ search_query }}" placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

          {% for profile in developers %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'users:profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{ profile.name }}</h3>
                    <h5>{{ profile.short_intro }}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{ profile.bio |slice:"120" }}
                </p>
                <div class="dev__skills">
                    {% for skill in profile.skill_set.all %}
                  <span class="tag tag--pill tag--main">
                    <small>{{ skill }}</small>
                  </span>
                    {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
    {% include 'pagination.html'  with queryset=developers custom_range=custom_range %}
  </main>
{% endblock %}

users/templates/users/user-profile.html
{% extends 'main.html' %}
{% block content %}
     <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.short_intro }}</p>
              <p class="dev__location">Based in {{ profile.location }}</p>
              <ul class="dev__social">
                <li>
                  <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                </li>
                <li>
                  <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
              </ul>
                {% if request.user.profile.id != profile.id %}
              <a href="{% url 'users:crate-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                {% endif %}

            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
                {% for skill in profile.skill_set.all %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ skill.name }}</h4>
                <p class="devSkill__info">
                  {{ skill.description }}
                </p>
              </div>
                {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Figma</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Vuejs</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>REST API</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>GraphQL</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>TypeScript</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Webpack</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>NextJS</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Postgres</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>MongoDB</small>
                </span>
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">DevSearch UI Design</h3>
                      <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">92%</span> Postitive
                        Feedback (62 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">Another Landing Page</h3>
                      <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">36%</span> Postitive
                        Feedback (18 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                      <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">98%</span> Postitive
                        Feedback (72 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}