Devsearsh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projects.urls')),
    path('',include('users.urls')),
    path('api/',include('api.urls')),

    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('reset_password_send/',auth_views.PasswordResetDoneView.as_view(template_name='reset_password_send.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passowrd_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_passord_complete/',auth_views.PasswordResetCompleteView.as_view(template_name = 'passowrd_reset_complete.html'),name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [

    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('',views.getRoutes),
    path('projects/',views.getProjects),
    path('projects/<str:pk>/',views.getProject),
    path('profiles/',views.getProfiles),
    path('profiles/<str:pk>',views.getProfile)
]

projects/urls.py
from django.urls import  path
from . import views

app_name = 'projects'
urlpatterns = [
    # path('',views.Home, name='home'),
    path('projects/',views.projects,name='projects'),
    path('project/<str:pk>',views.project, name='project'),
    path('create-project/',views.createProject, name='create-project'),
    path('update-project/<str:pk>',views.updateProject, name='update-project'),
    path('delete-project/<str:pk>',views.deleteProject, name='delete-project')
]

users/urls.py
from django.urls import path
from . import  views


app_name = 'users'
urlpatterns = [
    path('',views.profiles, name='profiles'),
    path('login/',views.loginUser, name='login'),
    path('register/',views.registerUser, name='register'),
    path('account/',views.userAccount, name='account'),
    path('add-skill/',views.addSkill,name='add-skill'),
    path('update-skill/<str:pk>/',views.updateSkill, name='update-skill'),
    path('delete-skill/<str:pk>',views.deleteSkill,name = 'delete-skill'),
    path('edit-account/',views.editAccount, name='edit-account'),
    path('logout/',views.logoutUser, name='logout'),
    path('profile/<str:pk>',views.userProfile, name= 'profile'),
    path('inbox/',views.inbox, name= 'inbox'),
    path('message/<str:pk>',views.viewMessage, name='message'),
    path('create-message/<str:pk>',views.createMessage,name='crate-message')

]

projects/models.py
from django.db import models
import uuid
from cloudinary.models import CloudinaryField
from users.models import Profile
# Create your models here.



class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    feautured_image = models.ImageField(default='default.jpg', blank=True,null=True)
    # feautured_image = CloudinaryField('image')
    tags = models.ManyToManyField('Tag',blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True , editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-vote_ratio','-vote_total','-created']

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id',flat=True)
        return  queryset


    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio

        self.save()

class Review(models.Model):
    VOTE_TYPE = (
        ('up','Up Value'),('down','Down Value')
    )
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    body = models.TextField(null=True,blank=True)
    value = models.CharField(max_length=200, null=True,choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.value

    class Meta:
        unique_together = ['owner','project']

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

projects/forms.py
from django.db.models.base import Model
from django.forms import ModelForm,widgets
from django import forms
from .models import Project,Review

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title','description'
            ,'feautured_image','demo_link','source_link']

        widgets = {
            'tags':forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})
        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': ' Add Title'})



class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['value','body']

        labels = {
                'value':'Place your vote',
                'body': 'Add a comment with your vote'
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

projects/views.py
from django.shortcuts import render, redirect
from .models import Project, Tag
from .forms import ProjectForm,ReviewForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .utils import searchProjects,paginateProjects


# Create your views here.

def Home(request):

    context ={

    }
    return render(request,'home.html',context)

def projects(request):
    projects, search_query = searchProjects(request)
    custom_range, projects = paginateProjects(request, projects, 3)

    context ={
        'projects':projects,'search_query':search_query,'custom_range':custom_range
    }
    return render(request, 'projects/projects.html', context)



def project(request, pk):
    projectObj = Project.objects.get(id=pk)
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.project = projectObj
            review.owner = request.user.profile
            review.save()
            projectObj.getVoteCount
            messages.success(request,'Your review was successfully submitted!')
            return redirect('projects:project',pk=projectObj.id)
    # tags = projectObj.tags.all()
    context={
        'project':projectObj,'form':form
        # 'tags':tags
    }
    return render(request, 'projects/single-project.html', context)

@login_required(login_url='users:login')
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', " ").split()
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            # print(request.POST)
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)

            return redirect('users:account')
    context = {
        'form':form
    }
    return render(request,'projects/project_form.html',context)


@login_required(login_url='users:login')
def updateProject(request,pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(','," ").split()
        print("DATA:" , newtags)
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            return redirect('users:account')
    context = {
        'form':form
    }
    return  render(request,'projects/project_form.html',context)


@login_required(login_url='users:login')
def deleteProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('projects:projects')
    context = {
        'object':project
    }
    return render(request,'delete_template.html',context)

projects/templates/projects/project_form.html
{% extends 'main.html' %}

{% block content %}

{#     <h1>Project Form</h1>#}
{#    <form action="" method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p}}#}
{#        {% for field in form %}#}
{#            <div>#}
{#                {{ field.label }} :#}
{#                {{ field }}#}
{#            </div>#}
{##}
{#        {% endfor %}#}
{#        <input type="submit" >#}
{#    </form>#}


    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'users:account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- Input:Text -->
                    {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label }} :  </label>

                    {{ field }}
                    </div>

                   {% endfor %}
                    <div class="form__field">
                         <label for="formInput#text">Tags</label>
                         <textarea class="input" name="newtags" placeholder="Add tages here ..."></textarea>
                    </div>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

projects/templates/projects/projects.html
{% extends 'main.html' %}
{% load static %}

{% block content %}


 <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'projects:projects' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                value="{{ search_query }}" placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">

        {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'projects:project' project.id %}" class="project">
                <img class="project__thumbnail" src="{{ project.feautured_image.url }}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{ project.title }}</h3>
                  <p><a class="project__author" href="{% url 'projects:project' project.id %}">{{ project.owner.name }}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                    Feedback ({{ project.vote_total  }} Vote{{ project.vote_total | pluralize:"s"}})

                  </p>
                  <div class="project__tags">
                     {% for tag in project.tags.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{ tag }}</small>
                    </span>
                   {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </section>
  {% include 'pagination.html'  with queryset=projects custom_range=custom_range %}
  </main>


{% endblock %}

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content%}

     <!-- Main Section -->
  <main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">
              {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{ tag }}</small>
            </span>
            {% endfor %}
          </div>
        {% if project.source_link %}
          <a class="singleProject__liveLink" href="{{ project.source_link }}"
             target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
        {% endif %}
        {% if project.demo_link %}
          <a class="singleProject__liveLink" href="{{ project.emo_link }}"
             target="_blank"><i class="im im-external-link"></i>Live Demo
          </a>
        {% endif %}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" style="width:500px" src="{{ project.feautured_image.url }}" alt="portfolio thumbnail" />
          <a href="profile.html" class="singleProject__developer">{{ project.owner }}</a>
          <h2 class="singleProject__title">{{ project.title }}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{ project.description }}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
                {{ project.vote_ratio }}% Postitive Feedback ({{ project.vote_total }}
                Vote{{ project.vote_total | pluralize:"s" }})
            </h5>

            {% if request.user.profile.id in project.reviewers  %}
             <p>You have already submitted your review for this project</p>
            {% elif requst.user.profile == project.owner %}
                <p>You can not review your own work!</p>
            {% elif request.user.is_authenticated %}
            <form class="form" action="{% url 'projects:project' project.id%}" method="POST">
             {% csrf_token %}
              <!-- Textarea -->
             {% for field in form %}
              <div class="form__field">
                <label for="formInput#textarea">{{ field.label }} </label>
                {{ field }}
              </div>
              {% endfor %}
              <input class="btn btn--sub btn--lg" type="submit" value="Add Review" />
            </form>
                {% else %}
                <a href="{% url 'users:login' %}?next={{ request.path }}">Please login to leave a review</a>
            {% endif %}


            <div class="commentList">
                {% for review in project.review_set.all %}
                {% if review.body %}
                  <div class="comment">
                     <a href="{% url 'users:profile' review.owner.id  %}">
                      <img class="avatar avatar--md" src="{{review.owner.profile_image.url}}" alt="user" />
                       </a>


                       <div class="comment__details">
                          <a href="{% url 'users:profile' review.owner.id  %}"
                              class="comment__author">{{review.owner.name}}</a>
                           <p class="comment__info">{{review.body|linebreaksbr}}</p>
                       </div>

                        </div>
                        {% endif %}
                        {% endfor %}

                    </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
{% endblock %}