Devsearsh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projects.urls')),
    path('',include('users.urls')),
    path('api/',include('api.urls')),

    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('reset_password_send/',auth_views.PasswordResetDoneView.as_view(template_name='reset_password_send.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passowrd_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_passord_complete/',auth_views.PasswordResetCompleteView.as_view(template_name = 'passowrd_reset_complete.html'),name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [

    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('',views.getRoutes),
    path('projects/',views.getProjects),
    path('projects/<str:pk>/',views.getProject),
    path('profiles/',views.getProfiles),
    path('profiles/<str:pk>',views.getProfile)
]

projects/urls.py
from django.urls import  path
from . import views

app_name = 'projects'
urlpatterns = [
    # path('',views.Home, name='home'),
    path('projects/',views.projects,name='projects'),
    path('project/<str:pk>',views.project, name='project'),
    path('create-project/',views.createProject, name='create-project'),
    path('update-project/<str:pk>',views.updateProject, name='update-project'),
    path('delete-project/<str:pk>',views.deleteProject, name='delete-project')
]

users/urls.py
from django.urls import path
from . import  views


app_name = 'users'
urlpatterns = [
    path('',views.profiles, name='profiles'),
    path('login/',views.loginUser, name='login'),
    path('register/',views.registerUser, name='register'),
    path('account/',views.userAccount, name='account'),
    path('add-skill/',views.addSkill,name='add-skill'),
    path('update-skill/<str:pk>/',views.updateSkill, name='update-skill'),
    path('delete-skill/<str:pk>',views.deleteSkill,name = 'delete-skill'),
    path('edit-account/',views.editAccount, name='edit-account'),
    path('logout/',views.logoutUser, name='logout'),
    path('profile/<str:pk>',views.userProfile, name= 'profile'),
    path('inbox/',views.inbox, name= 'inbox'),
    path('message/<str:pk>',views.viewMessage, name='message'),
    path('create-message/<str:pk>',views.createMessage,name='crate-message')

]

projects/models.py
from django.db import models
import uuid
from cloudinary.models import CloudinaryField
from users.models import Profile
# Create your models here.



class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    feautured_image = models.ImageField(default='default.jpg', blank=True,null=True)
    # feautured_image = CloudinaryField('image')
    tags = models.ManyToManyField('Tag',blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True , editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-vote_ratio','-vote_total','-created']

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id',flat=True)
        return  queryset


    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio

        self.save()

class Review(models.Model):
    VOTE_TYPE = (
        ('up','Up Value'),('down','Down Value')
    )
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    body = models.TextField(null=True,blank=True)
    value = models.CharField(max_length=200, null=True,choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.value

    class Meta:
        unique_together = ['owner','project']

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

projects/forms.py
from django.db.models.base import Model
from django.forms import ModelForm,widgets
from django import forms
from .models import Project,Review

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title','description'
            ,'feautured_image','demo_link','source_link']

        widgets = {
            'tags':forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})
        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': ' Add Title'})



class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['value','body']

        labels = {
                'value':'Place your vote',
                'body': 'Add a comment with your vote'
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

projects/views.py
from django.shortcuts import render, redirect
from .models import Project, Tag
from .forms import ProjectForm,ReviewForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .utils import searchProjects,paginateProjects


# Create your views here.

def Home(request):

    context ={

    }
    return render(request,'home.html',context)

def projects(request):
    projects, search_query = searchProjects(request)
    custom_range, projects = paginateProjects(request, projects, 3)

    context ={
        'projects':projects,'search_query':search_query,'custom_range':custom_range
    }
    return render(request, 'projects/projects.html', context)



def project(request, pk):
    projectObj = Project.objects.get(id=pk)
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.project = projectObj
            review.owner = request.user.profile
            review.save()
            projectObj.getVoteCount
            messages.success(request,'Your review was successfully submitted!')
            return redirect('projects:project',pk=projectObj.id)
    # tags = projectObj.tags.all()
    context={
        'project':projectObj,'form':form
        # 'tags':tags
    }
    return render(request, 'projects/single-project.html', context)

@login_required(login_url='users:login')
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', " ").split()
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            # print(request.POST)
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)

            return redirect('users:account')
    context = {
        'form':form
    }
    return render(request,'projects/project_form.html',context)


@login_required(login_url='users:login')
def updateProject(request,pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(','," ").split()
        print("DATA:" , newtags)
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            return redirect('users:account')
    context = {
        'form':form
    }
    return  render(request,'projects/project_form.html',context)


@login_required(login_url='users:login')
def deleteProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('projects:projects')
    context = {
        'object':project
    }
    return render(request,'delete_template.html',context)

templates/delete_template.html
{% extends 'main.html' %}
{% block content %}
     <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
{#                <a class="backButton" href="{% url 'users:account' %}"><i class="im im-angle-left"></i></a>#}
{#                <br>#}

                <form class="form" method="POST">
                    {% csrf_token %}
                    <p>Are your sure you want to delete this "{{ object }}"?</p>
                    <a class="btn btn--sub btn--lg  my-md" href="{{ request.GET.next }}">&#x2190 Go Back</a>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Delete" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

templates/form-template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="uikit/styles/uikit.css" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="styles/app.css" />

    <title>DevSearch - Connect with Developers!</title>
</head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
            <a href="/" class="header__logo">
                <img src="images/logo.svg" alt="DevSearch Logo" />
            </a>
            <nav class="header__nav">
                <input type="checkbox" id="responsive-menu" />
                <label for="responsive-menu" class="toggle-menu">
                    <span>Menu</span>
                    <div class="toggle-menu__lines"></div>
                </label>
                <ul class="header__menu">
                    <li class="header__menuItem"><a href="index.html">Developers</a></li>
                    <li class="header__menuItem"><a href="projects.html">Projects</a></li>
                    <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
                    <li class="header__menuItem"><a href="account.html">My Account</a></li>
                    <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</body>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
    {% include 'navbar.html' %}
    <h1>Welcome to Devsearch</h1>

    <a class="text" href="{% url 'projects:projects' %}">Projects List</a>
    <br>
    <a href="{% url 'projects:create-project' %}">Create New Project </a>
</body>
</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

  <title>DbSync - Database Synchronize!</title>
</head>

<body>
{% include 'navbar.html' %}
    <div class="text-center">

{#    {% if messages %}#}
{#       <ul class="messages">#}
{#          {% for message in messages %}#}
{#              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#          {% endfor %}#}
{#        </ul>#}
{#    {% endif %}#}
   {% if messages %}

    {% for message in messages %}
    <div class="alert  alert--{{message.tags}} ">
        <p class="alert__message">{{message}}</p>
        <button class="alert__close">X</button>
    </div>

    {% endfor %}

    {% endif %}

    </div>

    {% block content %}

    {% endblock %}
</body>
<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

templates/navbar.html
{% load static %}

{#<img src="{% static 'images/logo.svg' %}">#}
{#<a href="{% url 'projects:create-project' %}">Add Project</a>#}
{#<hr>#}
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="{% url 'projects:projects' %}" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'users:profiles' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects:projects'%}">Projects</a></li>


            {% if user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'users:inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'users:account'  %}">My Account</a></li>
          <li class="header__menuItem"><a href="{% url 'projects:create-project' %}" class="btn btn--sub">Add Project</a></li>
          <li class="header__menuItem"><a href="{% url 'users:logout' %}" class="btn btn--sub">Logout</a></li>
          {% else %}

          <li class="header__menuItem"><a href="{% url 'users:login' %}" class="btn btn--sub">Login/Sign Up</a></li>
            {% endif %}
        </ul>
      </nav>
    </div>
  </header>

templates/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination">
    <ul class="container">

        {% if queryset.has_previous %}
        <li><a href="?page={{queryset.previous_page_number}}" class="btn page-link"
                data-page="{{queryset.previous_page_number}}">&#10094; Prev</a></li>
        {% endif %}


        {% for page in custom_range %}

        {% if page == queryset.number%}
        <li><a href="?page={{page}}" class="btn page-link btn--sub" data-page="{{page}}">{{page}}</a></li>
        {% else %}
        <li><a href="?page={{page}}" class="btn page-link" data-page="{{page}}">{{page}}</a></li>
        {% endif %}
        {% endfor %}

        {% if queryset.has_next %}
        <li><a href="?page={{queryset.next_page_number}}" class="btn page-link"
                data-page="{{queryset.next_page_number}}">Next &#10095;</a></li>
        {% endif %}



    </ul>
</div>
{% endif %}

templates/passowrd_reset_complete.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
 <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">

                <h3>Password reset complete</h3>

                <br>
                <p>Your password has been set. You may go ahead and log in now.</p>

               <div class="auth__alternative">

                  <a href="{% url 'users:login' %}">Login</a>
               </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/passowrd_reset_confirm.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
 <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">


                <form class="form" method="POST">
                    {% csrf_token %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <h3>Reset Password</h3>
                        {{ form.as_p }}
                    </div>


                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock %}

templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="uikit/styles/uikit.css" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="styles/app.css" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="images/logo.svg" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="index.html">Developers</a></li>
          <li class="header__menuItem"><a href="projects.html">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>
          <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="https://avatars.githubusercontent.com/u/33843378" />
              <h2 class="dev__name">Dennis Ivanov</h2>
              <p class="dev__title">Expirance FullStack Developer, Youtuber and Instructor</p>
              <p class="dev__location">Based in Florida, USA</p>
              <ul class="dev__social">
                <li>
                  <a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
                </li>
                <li>
                  <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex illum ipsum iusto consequatur. Totam,
              dolorum fugiat, debitis facere illo nostrum nesciunt maxime, deserunt enim voluptatibus modi natus velit
              voluptatum. Dicta eritatis exercitationem ut quos a placeat obcaecati? Architecto illum!
              <br />
              Amet consectetur adipisicing elit. Veritatis exercitationem ut quos a placeat obcaecati? Architecto
              illum, atque delectus nemo dolorem inventore ab facilis? Dolor placeat vel delectus ipsam ullam.
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              <div class="devSkill">
                <h4 class="devSkill__title">JavaScript</h4>
                <p class="devSkill__info">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae neque voluptatum ut? Quaerat, ea
                  cumque! Dolorum provident esse molestias commodi odit sapiente quod quasi corrupti obcaecati? Nobis
                  ex temporibus quaerat!
                </p>
              </div>
              <div class="devSkill">
                <h4 class="devSkill__title">React</h4>
                <p class="devSkill__info">
                  Smet consectetur adipisicing elit. Omnis, nihil? Accusamus aspernatur aut debitis vitae quaerat
                  nihil fugiat, doloremque nesciunt alias pariatur maxime unde, nam saepe laborum at odit labore.
                </p>
              </div>
              <div class="devSkill">
                <h4 class="devSkill__title">Express(Nodejs)</h4>
                <p class="devSkill__info">
                  Auae error deleniti aperiam enim nisi nesciunt, ratione eveniet eos fuga ad recusandae mollitia!
                  Facere earum, distinctio nihil recusandae ipsum nesciunt. Possimus, ex. Officia maxime nihil
                  inventore cum tenetur! Veritatis sapiente libero ducimus nesciunt itaque, placeat inventore sint
                  blanditiis?
                </p>
              </div>

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Figma</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Vuejs</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>REST API</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>GraphQL</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>TypeScript</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Webpack</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>NextJS</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Postgres</small>
                </span>
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>MongoDB</small>
                </span>
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">DevSearch UI Design</h3>
                      <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">92%</span> Postitive
                        Feedback (62 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">Another Landing Page</h3>
                      <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">36%</span> Postitive
                        Feedback (18 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                      <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">98%</span> Postitive
                        Feedback (72 Votes)
                      </p>
                      <div class="project__tags">
                        <span class="tag tag--pill tag--main">
                          <small>NextJS</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>GraphQL</small>
                        </span>
                        <span class="tag tag--pill tag--main">
                          <small>TypeScript</small>
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>

</html>

templates/reset_password.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
       <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Forget Password?</h3>
          <p>Reset password by entering the email address</p>
        </div>

        <form action="#" class="form auth__form" method="post">
            {% csrf_token %}
          <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#email">Email Address: </label>
            <input
              class="input input--email"
              id="formInput#email"
              type="email"
              name="email"
              placeholder="e.g. user@domain.com"
            />
          </div>

          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Send Instructions" />
            <a href="{% url 'users:login' %}">Login</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'users:register' %}">Sign Up</a>
        </div>
      </div>
    </div>
  </body>
{% endblock %}